<?php if($this->editAllowed): ?>
	<div class="quote-info <?php echo $this->statusNotPaidClass;?> <?php echo ($this->allowAutoSave) ? 'allow-auto-save' : '';?>" id="<?php echo ($this->addressType == Widgets_Quote_Quote::ADDRESS_TYPE_BILLING) ? 'quote-billing-info' : 'quote-shipping-info';?>">
		<p class="title"><?php echo ($this->addressType == Widgets_Quote_Quote::ADDRESS_TYPE_BILLING) ? $this->translate('Billing info') : $this->translate('Shipped to'); ?>
            <span class="ticon-refresh use-lead-address pointer fl-right" data-type="<?php echo ($this->addressType == Widgets_Quote_Quote::ADDRESS_TYPE_BILLING) ? 'billing' : 'shipping';?>"> </span>
        </p>
		<?php echo $this->addressForm; ?>
	</div>
<?php elseif(!empty($this->quoteCustomParamsData) && !empty($this->customfieldsOptions)) :?>
    <?php foreach ($this->quoteCustomParamsData as $paramsData) :?>
        <?php if(in_array($paramsData['param_name'], $this->customfieldsOptions)) :?>
            <?php if($paramsData['param_type'] == Quote_Models_Model_QuoteCustomFieldsConfigModel::CUSTOM_PARAM_TYPE_TEXT) :?>
                <p><?php echo $paramsData['param_value'];?></p>
            <?php elseif ($paramsData['param_type'] == Quote_Models_Model_QuoteCustomFieldsConfigModel::CUSTOM_PARAM_TYPE_SELECT) :?>
                <p><?php echo $paramsData['option_val'];?></p>
            <?php elseif ($paramsData['param_type'] == Quote_Models_Model_QuoteCustomFieldsConfigModel::CUSTOM_PARAM_TYPE_RADIO) :?>

            <?php elseif ($paramsData['param_type'] == Quote_Models_Model_QuoteCustomFieldsConfigModel::CUSTOM_PARAM_TYPE_TEXTAREA) :?>

            <?php elseif ($paramsData['param_type'] == Quote_Models_Model_QuoteCustomFieldsConfigModel::CUSTOM_PARAM_TYPE_CHECKBOX) :?>

            <?php endif;?>
        <?php endif;?>
    <?php endforeach;?>
<?php else: ?>
	<?php if(!empty($this->address)): ?>
        <div class="quote-info" id="<?php echo ($this->addressType == Widgets_Quote_Quote::ADDRESS_TYPE_BILLING) ? 'quote-billing-info' : 'quote-shipping-info';?>">
            <p class="title"><?php echo ($this->addressType == Widgets_Quote_Quote::ADDRESS_TYPE_BILLING) ? $this->translate('Billing info') : $this->translate('Shipped to'); ?></p>
            <p><?php echo $this->address['firstname'], ' ', $this->address['lastname']; ?></p>
            <p><?php echo $this->address['company']; ?></p>
            <p>
                <?php echo $this->address['address1']; ?>
                <?php if($this->address['address2']): ?>
                    <?php echo ', ', $this->address['address2']; ?>
                <?php endif; ?>
            </p>
            <p>
                <?php echo $this->address['city'];?>
                <?php if($this->address['state']): ?>
                    <?php $stateData = Tools_Geo::getStateById($this->address['state']);?>
                    <?php echo ', ', $stateData['state'], ', '; ?>
                <?php endif; ?>
                <?php echo $this->address['zip']; ?>
            </p>
            <p>
                <?php if($this->address['country']):?>
                <?php $countries = Tools_Geo::getCountries(true); ?>
                <?php echo $countries[$this->address['country']];?>
                <?php endif; ?>
            </p>
            <p>
                <a href="mailto:<?php echo $this->address['email'];?>"><?php echo $this->address['email'];?></a>
            </p>
            <p><?php echo $this->address['phone_country_code_value'].$this->address['phone'];?></p>
        </div>
	<?php endif; ?>
<?php endif; ?>
<?php if(isset($this->addressForm)): ?>
    <script type="text/javascript">
        $(document).ready(function() {
            <?php if((!$this->address || !isset($this->address['state']) || !$this->address['state']) && empty($this->preventRemovingOptions)) : ?>
                $('#<?php echo $this->addressForm->getAttrib('id'); ?> select[name="state"]').empty().parent('div').hide();
            <?php endif; ?>

            var mobileMasks = JSON.parse('<?php echo json_encode($this->mobileMasks);?>'),
                desktopCountryCodeShipping =  $('#shipping-user-address select[name="phonecountrycode"]').val(),
                desktopCountryCodeBilling =  $('#plugin-quote-quoteform select[name="phonecountrycode"]').val(),
                mobileCountryCodeBilling =  $('#plugin-quote-quoteform select[name="mobilecountrycode"]').val(),
                mobileCountryCodeShipping = $('#shipping-user-address select[name="mobilecountrycode"]').val(),
                desktopMasks = JSON.parse('<?php echo json_encode($this->desktopMasks);?>');

            if (typeof desktopMasks[desktopCountryCodeShipping] !== 'undefined') {
                $('#shipping-user-address input[name="phone"]').mask(desktopMasks[desktopCountryCodeShipping].mask_value, {autoclear: false});
            } else {
                $('#shipping-user-address input[name="phone"]').mask('(999) 999 9999', {autoclear: false});
            }

            if (typeof desktopMasks[desktopCountryCodeBilling] !== 'undefined') {
                $('#plugin-quote-quoteform input[name="phone"]').mask(desktopMasks[desktopCountryCodeBilling].mask_value, {autoclear: false});
            } else {
                $('#plugin-quote-quoteform input[name="phone"]').mask('(999) 999 9999', {autoclear: false});
            }

            if (typeof mobileMasks[mobileCountryCodeBilling] !== 'undefined') {
                $('#plugin-quote-quoteform input[name="mobile"]').mask(mobileMasks[mobileCountryCodeBilling].mask_value, {autoclear: false});
            } else {
                $('#plugin-quote-quoteform input[name="mobile"]').mask('(999) 999 9999', {autoclear: false});
            }

            if (typeof mobileMasks[mobileCountryCodeShipping] !== 'undefined') {
                $('#shipping-user-address input[name="mobile"]').mask(mobileMasks[mobileCountryCodeShipping].mask_value, {autoclear: false});
            } else {
                $('#shipping-user-address input[name="mobile"]').mask('(999) 999 9999', {autoclear: false});
            }

            $(document).on('change', '#shipping-user-address select[name="phonecountrycode"]', function(e) {
                var countryEl = $(e.currentTarget),
                    chosenCountryCode = countryEl.val(),
                    desktopMasks = JSON.parse('<?php echo json_encode($this->desktopMasks);?>');

                if (typeof desktopMasks[chosenCountryCode] !== 'undefined') {
                    $('#shipping-user-address input[name="phone"]').mask(desktopMasks[chosenCountryCode].mask_value, {autoclear: false});
                } else {
                    $('#shipping-user-address input[name="phone"]').mask('(999) 999 9999', {autoclear: false});
                }
            });

            $(document).on('change', '#plugin-quote-quoteform select[name="phonecountrycode"]', function(e) {
                var countryEl = $(e.currentTarget),
                    chosenCountryCode = countryEl.val(),
                    desktopMasks = JSON.parse('<?php echo json_encode($this->desktopMasks);?>');

                if (typeof desktopMasks[chosenCountryCode] !== 'undefined') {
                    $('#plugin-quote-quoteform input[name="phone"]').mask(desktopMasks[chosenCountryCode].mask_value, {autoclear: false});
                } else {
                    $('#plugin-quote-quoteform input[name="phone"]').mask('(999) 999 9999', {autoclear: false});
                }
            });

            $(document).on('change', '#shipping-user-address select[name="mobilecountrycode"]', function(e) {
                var countryEl = $(e.currentTarget),
                    chosenCountryCode = countryEl.val(),
                    mobileMasks = JSON.parse('<?php echo json_encode($this->mobileMasks);?>');

                if (typeof mobileMasks[chosenCountryCode] !== 'undefined') {
                    $('#shipping-user-address input[name="mobile"]').mask(mobileMasks[chosenCountryCode].mask_value, {autoclear: false});
                } else {
                    $('#shipping-user-address input[name="mobile"]').mask('(999) 999 9999', {autoclear: false});
                }
            });

            $(document).on('change', '#plugin-quote-quoteform select[name="mobilecountrycode"]', function(e) {
                var countryEl = $(e.currentTarget),
                    chosenCountryCode = countryEl.val(),
                    mobileMasks = JSON.parse('<?php echo json_encode($this->mobileMasks);?>');

                if (typeof mobileMasks[chosenCountryCode] !== 'undefined') {
                    $('#plugin-quote-quoteform input[name="mobile"]').mask(mobileMasks[chosenCountryCode].mask_value, {autoclear: false});
                } else {
                    $('#plugin-quote-quoteform input[name="mobile"]').mask('(999) 999 9999', {autoclear: false});
                }
            });

            $(document).on('change', '#<?php echo $this->addressForm->getAttrib('id'); ?> select[name="country"]', function(e) {
                e.preventDefault();
                var self = this;
                $.getJSON($('#website_url').val() + 'api/store/geo/type/state?country=' + $(self).val(), function(response) {
                    var statesHolder = $('#<?php echo $this->addressForm->getAttrib('id'); ?> select[name="state"]');
                    if(!response.length) {
                        statesHolder.empty().parent('div').fadeOut();
                    } else {
                        statesHolder.empty().parent('div').fadeIn();
                        $.each(response, function(key, option) {
                            statesHolder.append($("<option></option>").attr("value", option.state).text(option.name))
                        })
                    }
                });
            });

       });
       </script>
       <?php endif; ?>
