<select name="quote-owner-list" id="quote-owners-list">
    <?php foreach ($this->quoteOwners as $quoteOwnerId => $quoteOwnerName): ?>
        <option <?php echo ($quoteOwnerId == $this->quoteOwnerId) ? 'selected' :'';?> value="<?php echo $quoteOwnerId;?>"><?php echo $quoteOwnerName;?></option>
    <?php endforeach; ?>
</select>

<script type="application/javascript">
    $(function () {
        $(document).on('change', '#quote-owners-list', function () {
            $.ajax({
                type: 'POST',
                url: '<?php echo $this->websiteUrl; ?>plugin/quote/run/changeQuoteOwner',
                data: {
                    quoteOwnerId: $(this).val(),
                    id: '<?php echo $this->id; ?>'
                }
            });
        });
    });
</script>