<div class="quote-controlls">
	<!-- add product to quote controll -->
    <a data-qid="<?php echo $this->quoteId; ?>" data-url="<?php echo $this->websiteUrl;?>plugin/quote/run/product/qid/<?php echo $this->quoteId; ?>" data-pheight="554" href="javascript:;" class="quote-control tpopup">
        <?php echo $this->translate('Add product'); ?>
    </a>

    <!-- save quote controll -->
	<a href="javascript:;" data-qid="<?php echo $this->quoteId; ?>" data-sendmail="0" class="quote-control save-action">
        <?php echo $this->translate('Save quote'); ?>
    </a>

    <!-- save quote and send e-mail controll -->
	<a href="javascript:;" data-qid="<?php echo $this->quoteId; ?>" data-sendmail="1" data-trigger="<?php echo Quote_Tools_QuoteMailWatchdog::TRIGGER_NEW_QUOTE; ?>" class="quote-control save-action">
        <?php echo $this->translate('Save and Send quote'); ?>
    </a>
</div>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'plugins/quote/web/js/misc/controls.js'); ?>