<div class="quote-controlls">
    <!-- Quote id -->
    <input type="hidden" name="hiddenQuoteId" id="quote-id" value="<?php echo $this->quoteId; ?>" />

    <!-- Current currency symbol -->
    <input type="hidden" name="currencySymbol" id="quote-currency" value="<?php echo $this->symbol; ?>" />

    <!-- add product to quote controll -->
    <a href="javascript:;" class="tpopup btn-toaster" data-url="<?php echo $this->websiteUrl;?>plugin/quote/run/product/qid/<?php echo $this->quoteId; ?>" data-pheight="560">
        <?php echo $this->translate('Add product'); ?>
    </a>

    <!-- save quote controll -->
	<a href="javascript:;" class="quote-control btn-toaster" data-sendmail="0">
        <?php echo $this->translate('Save quote'); ?>
    </a>

    <!-- save quote and send e-mail controll -->
	<a href="javascript:;" class="quote-control btn-toaster" data-sendmail="1" data-trigger="<?php echo ($this->status == Quote_Models_Model_Quote::STATUS_NEW) ? Quote_Tools_QuoteMailWatchdog::TRIGGER_QUOTE_CREATED : Quote_Tools_QuoteMailWatchdog::TRIGGER_QUOTE_UPDATED; ?>">
        <?php echo $this->translate('Save and Send quote'); ?>
    </a>

    <!-- preview quote controll -->
	<a href="<?php echo $this->websiteUrl;?><?php echo $this->quoteId; ?>.html?mode=preview" class="quote-control btn-toaster" target="_blank">
        <?php echo $this->translate('Preview quote'); ?>
    </a>
</div>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'plugins/quote/web/js/libs/accounting/accounting.min.js'); ?>
<script type="text/javascript">
    $(function() {
        accounting.settings.currency = <?php echo Zend_Json::encode(Tools_Misc::getCurrencyFormat()); ?>;
    });

</script>

<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'plugins/quote/web/js/misc/controls.min.js'); ?>
