<?php if($this->editAllowed): ?>

    <select name="discountRate" id="quote-discount-rate">
        <?php foreach($this->taxRates as $key => $value): ?>
            <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
        <?php endforeach; ?>
    </select>

    <input type="text" class="quote-recalculate" data-scope="quote-partial" data-type="discount" name="quoteDiscount" id="quote-discount"  value="<?php echo $this->discount; ?>" />
<?php else: ?>
    <?php echo $this->currency($this->discount); ?>
<?php endif; ?>