<?php if($this->editAllowed): ?>

    <select name="discountRate" id="quote-discount-rate">
        <?php foreach($this->taxRates as $key => $value): ?>
            <option value="<?php echo $key; ?>" <?php echo ($key == $this->rate) ? 'selected="selected"' : ''; ?>><?php echo $this->translate($value); ?></option>
        <?php endforeach; ?>
    </select>

    <input type="text" class="quote-recalculate" data-scope="quote-partial" data-type="discount" name="quoteDiscount" id="quote-discount"  value="<?php echo $this->discount; ?>" />
    <?php if (!empty($this->usNumericFormat)) : ?>
        <span id="quote-discount-with-tax"><?php echo number_format($this->discount + $this->discountTax, 2) . '&nbsp;' . $this->currencySymbol;?></span>
    <?php else:?>
        <?php if(!empty($this->clean)):?>
            <span id="quote-discount-with-tax"><?php echo number_format($this->discount + $this->discountTax, 2);?></span>
        <?php else:?>
            <span id="quote-discount-with-tax"><?php echo $this->currency($this->discount + $this->discountTax);?></span>
        <?php endif;?>
    <?php endif;?>
<?php else: ?>
    <?php if(($this->shoppingConfig['showPriceIncTax'])):?>
        <?php if (!empty($this->usNumericFormat)) : ?>
            <span class="quote-discount"><?php echo number_format($this->discount+$this->discountTax, 2) . '&nbsp;' . $this->currencySymbol; ?></span>
        <?php else :?>
            <?php if(!empty($this->clean)):?>
                <span class="quote-discount"><?php echo number_format($this->discount+$this->discountTax, 2); ?></span>
            <?php else:?>
                <span class="quote-discount"><?php echo $this->currency($this->discount+$this->discountTax); ?></span>
            <?php endif;?>
         <?php endif;?>
    <?php else:?>
        <?php if (!empty($this->usNumericFormat)) : ?>
            <span class="quote-discount"><?php echo number_format($this->discount, 2) . '&nbsp;' . $this->currencySymbol; ?></span>
        <?php else:?>
            <?php if(!empty($this->clean)):?>
                <span class="quote-discount"><?php echo number_format($this->discount, 2); ?></span>
            <?php else:?>
                <span class="quote-discount"><?php echo $this->currency($this->discount); ?></span>
            <?php endif;?>
        <?php endif;?>
    <?php endif;?>

<?php endif; ?>
