<?php
$websiteConfig = Zend_Controller_Action_HelperBroker::getExistingHelper('config')->getConfig();
?>
<?php echo $this->form; ?>

<script type="text/javascript">
    $(function() {
        <?php
        if(!Tools_Security_Acl::isAllowed(Shopping::RESOURCE_STORE_MANAGEMENT)):?>
            var grecaptchaContainer = document.createElement("div");
                grecaptchaContainer.classList.add('g-recaptcha');
            var grecaptchaPlace = $('#plugin-quote-quoteform input[type="submit"]');
                if (grecaptchaPlace.length) {
                  grecaptchaPlace.before(grecaptchaContainer);
                }
        <?php endif;?>
        if(!$('#state option').length) {
            $('#state').empty().parent('div').hide();
        }

        var mobileMasks = JSON.parse('<?php echo json_encode($this->mobileMasks);?>'),
            desktopCountryCodeShipping =  $('#shipping-user-address select[name="phonecountrycode"]').val(),
            desktopCountryCodeBilling =  $('#plugin-quote-quoteform select[name="phonecountrycode"]').val(),
            mobileCountryCodeBilling =  $('#plugin-quote-quoteform select[name="mobilecountrycode"]').val(),
            mobileCountryCodeShipping = $('#shipping-user-address select[name="mobilecountrycode"]').val(),
            desktopMasks = JSON.parse('<?php echo json_encode($this->desktopMasks);?>');

        if (typeof desktopMasks[desktopCountryCodeShipping] !== 'undefined') {
            $('#shipping-user-address input[name="phone"]').mask(desktopMasks[desktopCountryCodeShipping].mask_value, {autoclear: false});
        } else {
            $('#shipping-user-address input[name="phone"]').mask('(999) 999 9999', {autoclear: false});
        }

        if (typeof desktopMasks[desktopCountryCodeBilling] !== 'undefined') {
            $('#plugin-quote-quoteform input[name="phone"]').mask(desktopMasks[desktopCountryCodeBilling].mask_value, {autoclear: false});
        } else {
            $('#plugin-quote-quoteform input[name="phone"]').mask('(999) 999 9999', {autoclear: false});
        }

        if (typeof mobileMasks[mobileCountryCodeBilling] !== 'undefined') {
            $('#plugin-quote-quoteform input[name="mobile"]').mask(mobileMasks[mobileCountryCodeBilling].mask_value, {autoclear: false});
        } else {
            $('#plugin-quote-quoteform input[name="mobile"]').mask('(999) 999 9999', {autoclear: false});
        }

        if (typeof mobileMasks[mobileCountryCodeShipping] !== 'undefined') {
            $('#shipping-user-address input[name="mobile"]').mask(mobileMasks[mobileCountryCodeShipping].mask_value, {autoclear: false});
        } else {
            $('#shipping-user-address input[name="mobile"]').mask('(999) 999 9999', {autoclear: false});
        }

        $(document).on('change', '#shipping-user-address select[name="phonecountrycode"]', function(e) {
            var countryEl = $(e.currentTarget),
                chosenCountryCode = countryEl.val(),
                desktopMasks = JSON.parse('<?php echo json_encode($this->desktopMasks);?>');

            if (typeof desktopMasks[chosenCountryCode] !== 'undefined') {
                $('#shipping-user-address input[name="phone"]').mask(desktopMasks[chosenCountryCode].mask_value, {autoclear: false});
            } else {
                $('#shipping-user-address input[name="phone"]').mask('(999) 999 9999', {autoclear: false});
            }
        });

        $(document).on('change', '#plugin-quote-quoteform select[name="phonecountrycode"]', function(e) {
            var countryEl = $(e.currentTarget),
                chosenCountryCode = countryEl.val(),
                desktopMasks = JSON.parse('<?php echo json_encode($this->desktopMasks);?>');

            if (typeof desktopMasks[chosenCountryCode] !== 'undefined') {
                $('#plugin-quote-quoteform input[name="phone"]').mask(desktopMasks[chosenCountryCode].mask_value, {autoclear: false});
            } else {
                $('#plugin-quote-quoteform input[name="phone"]').mask('(999) 999 9999', {autoclear: false});
            }
        });

        $(document).on('change', '#shipping-user-address select[name="mobilecountrycode"]', function(e) {
            var countryEl = $(e.currentTarget),
                chosenCountryCode = countryEl.val(),
                mobileMasks = JSON.parse('<?php echo json_encode($this->mobileMasks);?>');

            if (typeof mobileMasks[chosenCountryCode] !== 'undefined') {
                $('#shipping-user-address input[name="mobile"]').mask(mobileMasks[chosenCountryCode].mask_value, {autoclear: false});
            } else {
                $('#shipping-user-address input[name="mobile"]').mask('(999) 999 9999', {autoclear: false});
            }
        });

        $(document).on('change', '#plugin-quote-quoteform select[name="mobilecountrycode"]', function(e) {
            var countryEl = $(e.currentTarget),
                chosenCountryCode = countryEl.val(),
                mobileMasks = JSON.parse('<?php echo json_encode($this->mobileMasks);?>');

            if (typeof mobileMasks[chosenCountryCode] !== 'undefined') {
                $('#plugin-quote-quoteform input[name="mobile"]').mask(mobileMasks[chosenCountryCode].mask_value, {autoclear: false});
            } else {
                $('#plugin-quote-quoteform input[name="mobile"]').mask('(999) 999 9999', {autoclear: false});
            }
        });

        $(document).on('submit', '#plugin-quote-quoteform', function(e) {
            e.preventDefault();

            //validate reuired fields firs
            var notValidElements = $('input.quote-required').filter(function() {
                return $(this).val() === '';
            }).css({borderColor: "indianred"});

            if(notValidElements.length) {
                showMessage('<?php echo $this->translate('Required fields are missing! Please fill all fields marked with *'); ?>', true);
                return false;
            }

            //working with form
            var form = $(e.currentTarget);

            //check if this is a single-product quote form
            var productId = $('#productId').val();
            if(productId != '') {
                var options = $('#product-'+productId+'-options-listing *').serialize();
                form.find('input[name="productOptions"]').val(options);
            }

            //console.log($(form).serialize()); return false;

            $.ajax({
                type: 'post',
                url: $(form).attr('action'),
                data: $(form).serialize(),
                dataType: 'json',
                beforeSend: showLoader('Sending quote...')
            }).done(function(response) {
                hideLoader();
                var formMessage = '<?php echo $this->translate('Thank you! The quote was generated for you. Our manager will contact you soon to clarify the details');?>';
                if(typeof response.error !== "undefined"){
                    showMessage(formMessage, false, 5000);
                    return false;
                }
                if($(form).hasClass('_reload') && (response instanceof Object)) {
                    window.location.href = response.id + '.html';
                } else {
                    showMessage(formMessage, false, 5000);
                    $.event.trigger({
                        type: "quoteForm-success"
                    });
                }
            }).fail(function(xhr, responseText, error) {
                hideLoader();
                var msg = '<a class="quote-fail-lnk" target="_blank" href="http://www.seotoaster.com/web-site-quote-system-software-tool.html">Learn more</a>';
                showMessage(xhr.responseText.replace(/"/g, '') + ' ' + msg, true);
            });

            return false;
        }).on('change', '#country', function(e) {
            var self = this;
            $.getJSON($('#website_url').val() + 'api/store/geo/type/state?country=' + $(self).val(), function(response) {
                var statesHolder = $('#plugin-quote-quoteform #state');
                if(!response.length) {
                    statesHolder.empty().parent('div').fadeOut();
                } else {
                    statesHolder.empty().parent('div').fadeIn();
                    $.each(response, function(key, option) {
                        statesHolder.append($("<option></option>").attr("value", option.state).text(option.name))
                    })
                }
            });
        })
    })
</script>
