<!-- quote grid row template -->
<script type="text/template" id="quote-grid-row">
    <td><input type="checkbox" class="quote-grid-row-checkbox" id="<%= id %>" <% if (this.model.get('checked')) {%>checked="checked"<% }%> /></td>
    <td><%= id %></td>
    <td>
    <% if (typeof userLink !== 'undefined' && userLink != '') { %>
        <a target="_blank" href="<%= userLink %>">
    <% } %>
        <%= (creatorId == 0) ? ownerName : (customerName === '') ? "<?php echo $this->translate('Not set'); ?>" : customerName %>
    <% if (typeof userLink !== 'undefined' && userLink != '') { %>
        </a>
    <% } %>

    </td>
    <td><a target="_blank" href="<%= $('#website_url').val() + id %>.html"><%= title %></a></td>
    <td><%= (ownerName != null) ? ownerName : "<?php echo $this->translate('unknown'); ?>" %></td>
    <td><%= $.datepicker.formatDate('dd-M-yy', new Date(Date.parse(createdAt.replace(/\-/g, '/')))) %></td>
    <td>
        <select name="quoteStatus" class="quote-status" id="<%= id %>">
            <option value="new" <% if (status == 'new') { %> selected="selected" <% } %>><?php echo $this->translate('Quote New');?></option>
            <option value="sent" <% if (status == 'sent') { %> selected="selected" <% } %>><?php echo $this->translate('Quote Sent');?></option>
            <option value="signature_only_signed" <% if (status == 'signature_only_signed') { %> selected="selected" <% } %>><?php echo $this->translate('Quote Signed (Signature only quote)');?></option>
            <option value="sold" <% if (status == 'sold') { %> selected="selected" <% } %>><?php echo $this->translate('Payment received');?></option>
            <option value="lost" <% if (status == 'lost') { %> selected="selected" <% } %>><?php echo $this->translate('Lost opportunity');?></option>
        </select>
    </td>
    <td><a target="_blank" href="<%= $('#website_url').val() + id %>.html?mode=preview"><?php echo $this->translate('Preview');?></a></td>
    <td class="text-center"><a href="javascript:;" class="quote-grid-delete icon18 ticon-cancel red" data-sid="<%= id %>"><?php echo $this->translate('Delete');?></a></td>
</script>
<!-- /quote grid row template -->
<input type="hidden" name="system-language" value="<?php echo Tools_Misc::getJsTranslationLanguage();?>"/>
<!-- paginator template -->
<?php echo $this->render('quote.grid.pager.phtml'); ?>
<!-- /paginator template -->

<?php if(Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_PLUGINS)): ?>
    <?php
        $this->headScript()
            ->appendFile($this->websiteUrl . 'plugins/shopping/web/js/libs/require.min.js', null, array('data-main' => $this->websiteUrl . 'plugins/quote/web/js/grid.js'));
        $this->headLink()
            ->appendStylesheet($this->websiteUrl . 'system/css/reset-widgets.css');
    ?>
    <div id="quote-grid">
        <div id="quote-grid-top" class="quote-grid-block mt20px mb20px clearfix">
            <div class="quote-grid-block-search grid_5 alpha border-box">
                <div class="quote-qrid-search">
                    <?php echo $this->formText('search', '', array('id' => 'quote-grid-search','class' => 'mb5px', 'placeholder' => $this->translate('search quote by title, by creator, by client email & name'))); ?>
                    <div class="grid_6 alpha">
                        <select name="quote-owner-name" id="quote-owner-name">
                            <option selected="selected" value=""><?php echo $this->translate('filter by owner');?></option>
                            <?php if(!empty($this->ownerRoles)) :?>
                                <?php foreach ($this->ownerRoles as $ownerId => $ownerFullName) :?>
                                    <option value="<?php echo $ownerId;?>"><?php echo $ownerFullName;?></option>
                                <?php endforeach;?>
                            <?php endif;?>
                        </select>
                    </div>
                    <div class="grid_6 omega">
                        <select name="quote-status-name" id="quote-status-name">
                            <option selected="selected" value=""><?php echo $this->translate('filter by status');?></option>
                            <option value="<?php echo Quote_Models_Model_Quote::STATUS_NEW;?>"><?php echo $this->translate('Quote New');?></option>
                            <option value="<?php echo Quote_Models_Model_Quote::STATUS_SENT;?>"><?php echo $this->translate('Quote Sent');?></option>
                            <option value="<?php echo Quote_Models_Model_Quote::STATUS_SIGNATURE_ONLY_SIGNED;?>"><?php echo $this->translate('Quote Signed (Signature only quote)');?></option>
                            <option value="<?php echo Quote_Models_Model_Quote::STATUS_SOLD;?>"><?php echo $this->translate('Payment received');?></option>
                            <option value="<?php echo Quote_Models_Model_Quote::STATUS_LOST;?>"><?php echo $this->translate('Lost opportunity');?></option>
                        </select>
                    </div>
                </div>
                <a href="javascript:;" id="search-quote-button" class="btn green"><?php echo $this->translate('Search Quote');?></a>
                <?php $quoteTemplates = array_merge(
                    array(0 => 'Select quote template'),
                    Tools_System_Tools::getTemplatesHash(Quote_Models_Model_Quote::TEMPLATE_TYPE_QUOTE)
                );?>
            </div>
            <div class="flex-row-quote-buttons grid_7 alpha omega border-box">
                <div class="btn-group">
                    <button class="quote-create-option-button btn checked-btn"
                            name="quote-create-option-button-create" data-checked="true"
                            data-type="create_new_quote"><?php echo $this->translate('Create a new quote'); ?></button>
                    <button class="quote-create-option-button btn"
                            name="quote-create-option-button-clone" data-checked="false"
                            data-type="create_quote_duplicate"><?php echo $this->translate('Create quote from a template'); ?></button>
                </div>

                <input class="hidden" id="search-quote-duplicate" name="search-quote-duplicate" placeholder="<?php echo $this->translate('Search by quote title');?>" />
                <input type="text" id="quote-title-original" class="search-quote-title-original" placeholder="<?php echo $this->translate('Quote title');?>" />
                <input class="hidden" id="duplicate-quote-id" name="duplicate-quote-id">
                <input id="quote-chosen-type" class="quote-chosen-type" type="hidden" name="quote-chosen-type" value="">

                <a class="quote-grid-add btn green" href="javascript:;" title="<?php echo $this->translate('Create Quote');?>"><?php echo $this->translate('Create Quote');?></a>
            </div>
        </div>
        <table id="quote-grid-quotes" class="widget table-hover">
            <thead>
                <tr class="ws-nowrap">
                    <th><input type="checkbox" id="quote-grid-select-all" /></th>
                    <th data-sort="id" class="sortable"><?php echo $this->translate('Id'); ?></th>
                    <th data-sort="clients" class="sortable"><?php echo $this->translate('Client'); ?></th>
                    <th data-sort="title" class="sortable"><?php echo $this->translate('Title'); ?></th>
                    <th data-sort="ownerName" class="sortable"><?php echo $this->translate('Owner'); ?></th>
                    <th data-sort="created_at" class="sortable"><?php echo $this->translate('Date'); ?></th>
                    <th data-sort="status" class="sortable"><?php echo $this->translate('Status'); ?></th>
                    <th><?php echo $this->translate('Preview'); ?></th>
                    <th class="text-center"><?php echo $this->translate('Remove'); ?></th>
                </tr>
            </thead>
            <tbody>
                <td class="text-center" colspan="9">
                    <?php if(isset($this->quotes['total']) && ($this->quotes['total'] > 0)): ?>
                        <img src="<?php echo $this->websiteUrl;?>system/images/spinner-small.gif" border="0" alt="loading..." />
                    <?php else: ?>
                        <?php echo $this->translate('There are no quotes, yet'); ?>.
                        <a href="javascript:;" class="quote-grid-add"><?php echo $this->translate('Add one now'); ?>?</a>
                    <?php endif; ?>
                </td>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="2">
    					<?php echo $this->translate('With selected'); ?>
                        <?php echo $this->formSelect('withSelected', $this->translate('select an action'), array('id' => 'batch-action'), array(
                            '0'      => $this->translate('select an action'),
                            'remove' => $this->translate('Remove'),
                        )); ?>
    				</td>
                    <td class="pager text-right" colspan="7"></td>
                </tr>
            </tfoot>
        </table>
    </div>
<?php endif; ?>

<?php if(isset($this->quotes['total']) && ($this->quotes['total'] > 0)): ?>
    <script type="text/javascript">
        $(function() {
            $(document).one('grid:loaded', function() {
                appView.quotes.paginator_ui = _.extend(appView.quotes.paginator_ui, {
                    perPage: <?php echo Widgets_Quote_Quote::QUOTEGRID_DEFAULTS_PERPAGE; ?>
                });
                appView.quotes.init(<?php echo Zend_Json::encode($this->quotes); ?>);
            });
        });
    </script>
<?php endif; ?>
<style type="text/css">
    .sortable {cursor: pointer;}
</style>
