<?php if(!empty($this->options)): ?>

	<?php foreach($this->options as $optData): ?>
	    <p>
		    <?php echo $optData['title']; ?>
		    <?php echo '<br />(', $optData['priceSign'], $this->currency($optData['priceValue']), ')'; ?>
		    <?php echo '<br />(', $optData['weightSign'], $optData['weightValue'], ' ', $this->weightSign, ')'; ?>
	    </p>
	<?php endforeach; ?>

<?php endif; ?>
<?php if(Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_ADMINPANEL)): ?>
	<a href="javascript:;" data-pwidth="600" data-pheight="404" class="tpopup" data-url="<?php echo $this->websiteHelper; ?>plugin/quote/run/options/pid/<?php echo $this->quoteItem['id'];?>">
		<strong><?php echo $this->translate('Manage options'); ?></strong>
	</a>
<?php endif; ?>
