<div id="quote-payment-type-config-block">
    <?php if ($this->accessAllowed === true): ?>
        <p><label><?php echo $this->translate('Payment type'); ?></label>
            <select
                <?php echo (($this->quoteStatus === Quote_Models_Model_Quote::STATUS_SOLD) ? 'disabled' : '') ?> id="quote-payment-type-selector"
                name="quote-payment-type-selector">
                <option <?php echo((Quote_Models_Model_Quote::PAYMENT_TYPE_FULL === $this->paymentType) ? 'selected' : ''); ?>
                        value="<?php echo Quote_Models_Model_Quote::PAYMENT_TYPE_FULL; ?>"><?php echo $this->translate('Full Payment required'); ?></option>
                <?php if($this->partialPaymentAllowed === true): ?>
                                <option <?php echo((Quote_Models_Model_Quote::PAYMENT_TYPE_PARTIAL_PAYMENT === $this->paymentType) ? 'selected' : ''); ?> value="<?php echo Quote_Models_Model_Quote::PAYMENT_TYPE_PARTIAL_PAYMENT; ?>"><?php echo $this->translate('Partial Payment required'); ?></option>
                <?php endif;?>
                <option <?php echo((Quote_Models_Model_Quote::PAYMENT_TYPE_ONLY_SIGNATURE === $this->paymentType) ? 'selected' : ''); ?>
                        value="<?php echo Quote_Models_Model_Quote::PAYMENT_TYPE_ONLY_SIGNATURE; ?>"><?php echo $this->translate('Only Signature required'); ?></option>
            </select>
        </p>
        <p>
            <label><?php echo $this->translate('Pdf template'); ?></label>
            <select <?php echo (($this->quoteStatus === Quote_Models_Model_Quote::STATUS_SOLD) ? 'disabled' : '') ?> id="quote-pdf-template-selector" name="quote-pdf-template-selector">
                <option value="0"><?php echo $this->translate('No template'); ?></option>
                <?php if (!empty($this->pdfTemplates)): ?>
                    <?php foreach ($this->pdfTemplates as $template): ?>
                        <option <?php echo(($template->getName() === $this->pdfTemplate) ? 'selected' : ''); ?>
                                value="<?php echo $template->getName(); ?>"><?php echo $template->getName(); ?></option>
                    <?php endforeach; ?>
                <?php endif; ?>
            </select>
        </p>
        <p class="signature-required-block">
            <label><?php echo $this->translate('Signature required'); ?></label>
            <input <?php echo((Quote_Models_Model_Quote::PAYMENT_TYPE_ONLY_SIGNATURE === $this->paymentType || $this->quoteStatus === Quote_Models_Model_Quote::STATUS_SOLD) ? 'disabled' : ''); ?>  <?php echo(($this->isSignatureRequired == '1') ? 'checked' : ''); ?>
                    id="quote-signature-required"
                    name="quote-signature-required"
                    type="checkbox"/>
        </p>
    <?php endif; ?>
    <input type="hidden" id="quote-id-payment-type" name="quote-id-payment-type" value="<?php echo $this->quoteId; ?>">
</div>



