<?php echo $this->formText('quoteSearch', '', array(
	'id'          => 'quote-search',
	'placeholder' => $this->translate('Start typing name or e-mail to search among addresses'),
	'class'       => 'quote-address-search'
)); ?>
<script type="text/javascript">
	$(function() {
        var searchBox  = $('#quote-search');
        searchBox.autocomplete({
            source: function(request, callback) {
                $.getJSON($('#website_url').val() + 'api/quote/customers/search/' + request.term, callback);
            },
            minLength: 2,
            select: function(event, ui) {
                var billingForm = $('#plugin-quote-quoteform');
                console.log(ui.item);
                if(ui.item.state) {

                }


                $(':input[name]', billingForm).each(function() {
                    $(this).val(ui.item[$(this).attr('name')]);
                });
                if($('#same-for-shipping').attr('checked')) {
                    var shippingForm = $('#shipping-user-address');
                    $(':input[name]', shippingForm).each(function() {
                        $(this).val(ui.item[$(this).attr('name')]);
                    });
                }
            }
        }).data('ui-autocomplete')._renderItem = function(ul, item) {
            return $('<li></li>')
                .data('ui-autocomplete-item', item)
                .append('<a><strong>Quote: #' + item.id + '</strong><br/>' + item.firstname + ' ' + item.lastname +
                    '<br/> ' + item.email + '<br/> Address type: ' + item.address_type + '</a>')
                .appendTo(ul);
        };
    });
</script>
<style type="text/css">
    .ui-autocomplete {
        max-height: 280px;
        overflow-y: auto;
        overflow-x: hidden;
        padding-right: 5px;
        background: url('/system/images/bg-strip.png');
        box-shadow: #999 0px 4px 10px;
    }
</style>