<?php if($this->editAllowed): ?>
    <input type="text" name="quoteShipping" data-scope="quote-partial" data-type="shipping" id="quote-shipping-price" class="quote-recalculate" value="<?php echo $this->quoteShipping; ?>" />
    <?php if (!empty($this->usNumericFormat)) : ?>
        <span id="quote-shipping-with-tax"><?php echo number_format($this->quoteShipping + $this->shippingTax, 2) . '&nbsp;' . $this->currencySymbol;?></span>
    <?php else :?>
        <span id="quote-shipping-with-tax"><?php echo $this->currency($this->quoteShipping + $this->shippingTax);?></span>
    <?php endif;?>
<?php else: ?>
    <?php if(($this->shoppingConfig['showPriceIncTax'])):?>
        <?php if (!empty($this->usNumericFormat)) : ?>
            <span id="quote-shipping-price"><?php echo number_format($this->quoteShipping + $this->shippingTax, 2) . '&nbsp;' . $this->currencySymbol;?></span>
        <?php else :?>
            <span id="quote-shipping-price"><?php echo $this->currency($this->quoteShipping + $this->shippingTax);?></span>
        <?php endif;?>
    <?php else:?>
        <?php if (!empty($this->usNumericFormat)) : ?>
            <span id="quote-shipping-price"><?php echo number_format($this->quoteShipping, 2) . '&nbsp;' . $this->currencySymbol; ?></span>
        <?php else:?>
            <span id="quote-shipping-price"><?php echo $this->currency($this->quoteShipping); ?></span>
        <?php endif;?>
    <?php endif;?>
<?php endif; ?>
