<script src="https://cdn.jsdelivr.net/npm/signature_pad@2.3.2/dist/signature_pad.min.js"></script>

<?php $signatureInfoClass = '';?>
<?php if ($this->withSignatureInfoField === true) :?>
    <?php if (empty($this->signatureInfoField)):?>
        <?php $signatureInfoClass = 'hidden';?>
    <?php endif;?>
<?php endif;?>


<div id="quote-signature-block" class="<?php echo $this->signatureClass;?>">
    <?php if (empty($this->isQuoteSigned)) :?>
        <?php if ($this->accessAllowed === true):?>
                <?php if ($this->withSignatureInfoField === true) :?>
                {$header:signatureinfofieldtext:static}
<!--                    <label class="signature-info-label">--><?php //echo $this->signatureInfoLabel;?><!--</label>-->
                    <textarea id="signature-info-field"><?php echo $this->signatureInfoField;?></textarea>
                <?php endif;?>
                <span><?php echo $this->translate('Signature');?>:</span>
                <div>
                    <img src="<?php echo $this->websiteUrl.'plugins/quote/web/images/signature-placeholder.png';?>">
                    <p><?php echo $this->translate('Client signature will be here');?>:</p>
                </div>
        <?php else:?>
            <?php if ($this->withSignatureInfoField === true && empty($this->isSignatureSigned)) :?>
<!--                <label class="signature-info-label">--><?php //echo $this->signatureInfoLabel;?><!--</label>-->
                {$header:signatureinfofieldtext:static}
                <textarea id="signature-info-field"><?php echo $this->signatureInfoField;?></textarea>
            <?php endif;?>
            <span id="quote-signature-form-label" class="<?php echo $signatureInfoClass;?>"><?php echo $this->translate('Sign here using cursor or finger on your smartphone');?>:</span>
            <form class="<?php echo $signatureInfoClass;?>" id="quote-signature-form">
                <div id="quote-signature-form-refresh" name="quote-signature-form-refresh">
                    <img id="quote-signature-form-clear" src="<?php echo $this->websiteUrl.'plugins/quote/web/images/refresh.png';?>" alt="<?php echo $this->translate('Clear Signature')?>">
                </div>
                <div id="signature-block">
                    <canvas id="quote-signature-pad" width="450" height="270"></canvas>
                </div>
                <input class="hidden" type="text" name="quote-signature-form-img" id="quote-signature-form-img">
                <input class="hidden" type="text" name="signature-quote-id" id="signature-quote-id" value="<?php echo $this->quoteId;?>">
                <input name="submit-quote-signature-form" type="submit" value="<?php echo $this->translate('Click here to validate signature and accept proposal');?>">
            </form>
        <?php endif;?>
    <?php else :?>
        <?php if ($this->withSignatureInfoField === true) :?>
            <?php if ($this->accessAllowed === true):?>
<!--                <label class="signature-info-label">--><?php //echo $this->signatureInfoLabel;?><!--</label>-->
                {$header:signatureinfofieldtext:static}
                <textarea id="signature-info-field"><?php echo $this->signatureInfoField;?></textarea>
            <?php else:?>
                <span class="signature-info-field-result"><?php echo $this->signatureInfoField;?></span>
            <?php endif;?>
        <?php endif;?>
        <img id="quote-signature-signed-img" src="<?php echo $this->signature;?>">
    <?php endif;?>
</div>

<script>
    $(document).ready(function() {
        if ($('#quote-signature-pad').length > 0) {
            var signaturePad = new SignaturePad(document.getElementById('quote-signature-pad'), {
                backgroundColor: 'rgba(255, 255, 255, 0)',
                penColor: 'rgb(0, 0, 0)'
            });

            var cancelButton = document.getElementById('quote-signature-form-clear');

            $(document).on('submit', '#quote-signature-form', function (e) {
                var data = signaturePad.toDataURL('image/png');
                $('#quote-signature-form-img').val(data);
            });

            cancelButton.addEventListener('click', function (event) {
                signaturePad.clear();
            });
        }

        $(document).on('submit','#quote-signature-form', function(e){
            e.preventDefault();

            var form = $(e.currentTarget),
                quoteId = form.find('#signature-quote-id').val(),
                signature = form.find('#quote-signature-form-img').val();

            showConfirmCustom('<?php echo $this->translate('Are you happy with your signature?');?>', '<?php echo $this->translate('Yes');?>', '<?php echo $this->translate('No');?>', function() {
                $.ajax({
                    url        : $('#website_url').val() + 'api/quote/signature/',
                    type       : 'POST',
                    data       : {
                        'quoteId': quoteId,
                        'signature': signature
                    },
                    dataType   : 'json',
                    beforeSend : showSpinner()
                }).done(function(response) {
                    hideSpinner();
                    if (response.error == '0') {
                        if (typeof response.responseText.reload !== 'undefined') {
                            showMessage(response.responseText.message, true, 3000);
                            window.setTimeout(function () {
                                window.location.reload();
                            }, 2000);
                            return false;
                        }

                        showMessage(response.responseText, false, 5000);
                        $('#quote-signature-form').replaceWith('<img id="quote-signature-signed-img" src="'+signature+'">');
                    }
                }).fail(function (response) {
                    showMessage(JSON.parse(response.responseText), true, 5000);
                });
            });
        });

        $(document).on('blur', '#signature-info-field', function () {
            var signatureInfoField = $(this).val();

            if (signatureInfoField) {
                $('#quote-signature-form').removeClass('hidden');
                $('#quote-signature-form-label').removeClass('hidden');
            } else {
                $('#quote-signature-form').addClass('hidden');
                $('#quote-signature-form-label').addClass('hidden');
            }

            $.ajax({
                url: $('#website_url').val() + 'plugin/quote/run/saveSignatureInfoField',
                data: {'quoteId': '<?php echo $this->quoteId;?>', 'signatureInfoField': signatureInfoField},
                type: 'post',
                dataType: 'json'
            }).done(function (response) {
                if (response.error == '1') {
                    showMessage(response.responseText, true, 5000);
                    return false;
                } else {
                    //showMessage(response.responseText, false, 3000);
                }
            });
        });
    });
</script>


<style>
    #signature-block {
        height: 270px;
        width: 450px;
        z-index: 99;
    }

    #signature-pad {
        border-width: 2px;
        border-style: dashed;
        border-color: rgb(221, 221, 221);
        background-color: rgb(235, 235, 235);
        cursor: url(<?php echo $this->websiteUrl.'plugins/quote/web/images/pen.cur';?>), pointer;
        width: 450px;
        height: 270px;
    }

    #quote-signature-form-refresh {
        margin:5px;
        position:relative;
        height:20px;
        width:450px;
        background-color:transparent;
    }

    #quote-signature-form-clear {
        cursor:pointer;
        float:right;
        height:24px;
        width:24px;
        border:0px solid transparent;
    }
</style>