<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><?php echo $this->translate('Manage quotes'); ?></title>
		<meta name="description" content="<?php echo $this->translate('Manage quotes'); ?>">
		<meta name="author" content="SEOTOASER 2">
		<meta name="viewport" content="width=device-width">

		<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/reset.css')
                ->appendStylesheet($this->websiteUrl . 'system/css/grid.css')
                ->appendStylesheet($this->websiteUrl . 'system/uithemes/seotoasterui/seotoasterui.css')
                ->appendStylesheet($this->websiteUrl . 'system/css/seotoaster.css')
                ->appendStylesheet($this->websiteUrl . 'system/js/external/smoke/smoke.css')
                ->appendStylesheet($this->websiteUrl . 'system/js/external/smoke/themes/toaster.css')
				->appendStylesheet($this->websiteUrl . 'plugins/quote/web/css/add.products.quote.css'); ?>
        <?php echo $this->headLink(); ?>

		<!-- product template -->
		<script id="productTemplate" type="text/x-jquery-tmpl">
			<p class="brand">${brand}</p>
			<img class="lazy" src="" data-original="{{if photo}}${'/media/'+photo.replace('/', '/product/')}{{else}}/system/images/noimage.png{{/if}}" alt="${name}" />
			<p class="name">${name}</p>
			<p class="sku">${sku}</p>
			<a class="btn-add" data-pid="${id}" href="javascript:;"><?php echo $this->translate('Add'); ?></a>
		</script>

		<!-- filters -->
		<script id="filtersTemplate" type="text/x-jquery-tmpl">

		</script>
	</head>
	<body>
		<input type="hidden" id="pluginUrl" name="pluginUrl" value="<?php echo trim($this->websiteUrl, ' /').$this->url(array('run'=>''));?>" />
	    <input type="hidden" id="websiteUrl" name="websiteUrl" value="<?php echo $this->websiteUrl;?>" />
		<input type="hidden" id="website_url" name="websiteUrl" value="<?php echo $this->websiteUrl;?>" />
		<div class="seotoaster container_12 h550 refreshOnClose" id="add-products-quote">
			<div class="header" style="overflow:hidden;">
				<div class="closebutton">
				    <span class="close"><?php echo $this->translate('Close'); ?></span>
				</div>
				<?php echo $this->translate('Add products to the quote'); ?>
			</div>
			<div id="products" class="ui-widget-content ui-helper-clearfix h450 grid_12" style="overflow-x: hidden; overflow-y: auto;">

			</div>
			<div class="grid_12 mt10px">
				<button class="save-and-close <?php echo $this->extraClasses; ?>"><?php echo $this->translate('Save and close'); ?></button>
			</div>
   	    </div>
	</body>
	<?php
        $this->headScript()->setAllowArbitraryAttributes(true)
                ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js')
                ->appendFile('https://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js')
                ->appendFile($this->websiteUrl . 'system/js/external/jquery/plugins/tmpl/jquery.tmpl.min.js')
                ->appendFile($this->websiteUrl . 'system/js/external/jquery/plugins/lazyload/jquery.lazyload.min.js')
                ->appendFile($this->websiteUrl . 'system/js/external/smoke/smoke.min.js')
                ->appendFile($this->websiteUrl . 'plugins/quote/web/js/libs/require/require.js', null, array('data-main' => $this->websiteUrl . 'plugins/quote/web/js/product.js'))
                ->appendFile($this->websiteUrl . 'system/js/internal/system.js');
        echo $this->headScript();
    ?>
</html>
