<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><?php echo $this->translate('Build a quote'); ?></title>
		<meta name="description" content="<?php echo $this->translate('Manage quotes'); ?>">
		<meta name="author" content="SEOTOASER 2">
		<meta name="viewport" content="width=device-width">
	   	
		<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/reset.css')
                ->appendStylesheet($this->websiteUrl . 'system/uithemes/seotoasterui/seotoasterui.css')
                ->appendStylesheet($this->websiteUrl . 'system/css/seotoaster.css')
                ->appendStylesheet($this->websiteUrl . 'system/js/external/smoke/smoke.css')
                ->appendStylesheet($this->websiteUrl . 'system/js/external/smoke/themes/toaster.css')
				->appendStylesheet($this->websiteUrl . 'plugins/quote/web/css/build.quote.css'); ?>
        <?php echo $this->headLink(); ?>

	</head>
	<body>
	    <div id="quote-main">
		    <div id="quote-main-inner">

			    <div id="quote-quicksearch">
					quick search
				</div>

			    <div id="quote-tophead">
					tophead
				</div>

			    <div id="quote-content">

					<div id="quote-title">
						<div id="quote-title-inner">
							<h1><?php echo $this->translate('Quote'); ?> #</h1>
							<input type="text" name="quoteName" value="" id="quote-name"/>
						</div>
					</div>

					<div id="quote-cart">
						<table>
							<thead>
								<tr>
									<th><?php echo $this->translate('Photo'); ?></th>
									<th><?php echo $this->translate('Product'); ?></th>
									<th><?php echo $this->translate('Note'); ?></th>
									<th><?php echo $this->translate('Qty'); ?></th>
									<th><?php echo $this->translate('Price'); ?></th>
									<th><?php echo $this->translate('Total'); ?></th>
								</tr>
							</thead>
							<tbody>
								<?php if(isset($this->cartContent) && !empty($this->cartContent)): ?>
									<?php foreach($this->cartContent as $sid => $cartItem): ?>
										<tr>
											<td><?php echo $cartItem['photo']; ?></td>
											<td><?php echo $cartItem['name']; ?></td>
											<td><input type="text" name="quoteCartNote[<?php echo $sid; ?>]" value="" /></td>
											<td><input type="number" step="1" min="1" name="quoteCartQty[<?php echo $sid; ?>]" value="<?php echo $cartItem['qty']; ?>"/></td>
											<td><input type="text" name="quoteCartPrice[<?php echo $sid; ?>]" value="<?php echo $cartItem['price']; ?>" /></td>
											<td><?php echo ($cartItem['price'] * $cartItem['qty']); ?></td>
										</tr>
									<?php endforeach; ?>
								<?php else: ?>
									<td colspan="6" id="empty-cart"><?php echo $this->translate('Cart is empty'); ?></td>
								<?php endif; ?>
							</tbody>
						</table>
					</div>
					<div id="quote-summary">
						<div id="summary-stat" class="qsummary">
							<div class="summary-stat-row">
								<span><?php echo $this->translate('Sub-total'); ?></span>
								<span>0</span>
							</div>
							<div class="summary-stat-row">
								<span><?php echo $this->translate('Tax'); ?></span>
								<span>0</span>
							</div>
							<?php if($this->shippingType != Tools_Shipping_Shipping::SHIPPING_TYPE_PICKUP): ?>
								<div class="summary-stat-row">
									<span><?php echo $this->translate('Shipping'); ?></span>
									<span>0</span>
								</div>
							<?php endif; ?>
							<div class="summary-stat-row">
								<span><?php echo $this->translate('Discount'); ?></span>
								<span>0</span>
							</div>
							<hr/>
							<div class="summary-stat-row">
								<span><?php echo $this->translate('Grand Total'); ?></span>
								<span>0</span>
							</div>
						</div>
						<div id="shipping-type" class="qsummary">

						</div>
					</div>
					<div id="quote-services">

					</div>
				</div>
		    </div>
	    </div>
	    <div style="height: 30px; min-height: 30px;"></div>
	    <footer id="bottom-line">
		    <div id="footer-inner">
			    <a data-url="<?php echo $this->websiteUrl;?>plugin/quote/run/additem/" data-pheight="551" href="javascript:;" class="quote-controll tpopup"><?php echo $this->translate('Add product'); ?></a>
			    <a href="" class="quote-controll"><?php echo $this->translate('Save quote'); ?></a>
                <a href="" class="quote-controll"><?php echo $this->translate('Save and Send quote'); ?></a>
                <span><?php echo $this->translate('Last edited by: '), $this->lastEditedBy; ?></span>
		    </div>
	    </footer>
	</body>
	<?php
        $this->headScript()->setAllowArbitraryAttributes(true)
                ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js')
                ->appendFile('https://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js')
                ->appendFile($this->websiteUrl . 'system/js/external/jquery/plugins/cookie/jquery.cookie.js')
                ->appendFile($this->websiteUrl . 'system/js/external/smoke/smoke.min.js')
                ->appendFile($this->websiteUrl . 'system/js/internal/system.js');
        echo $this->headScript();
    ?>
	<script type="text/javascript">
		$(function() {
			$('.quote-controll').button();
		});
	</script>
</html>
