<?php echo $this->doctype();?>
<!--[if IE 7 ]><html class="ie ie7" lang="<?php echo $this->htmlLang; ?>"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="<?php echo $this->htmlLang; ?>"> <![endif]-->
<!--[if IE 9 ]><html class="ie ie9" lang="<?php echo $this->htmlLang; ?>"> <![endif]-->
<!--[if !(IE)]><!-->
<html lang="<?php echo $this->htmlLang; ?>">
<!--<![endif]-->
    <head>
	    <?php
		    $this->headMeta()->setCharset('UTF-8');
	        $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
                 ->appendHttpEquiv('Content-Language', $this->translate()->getLocale());
	        echo $this->headMeta();
            echo $this->headTitle();
	        $this->headLink()
                ->prependStylesheet($this->websiteUrl . 'plugins/shopping/web/css/store.css')
                ->prependStylesheet($this->websiteUrl . 'system/css/seotoaster.css')
                ->prependStylesheet($this->websiteUrl . 'system/css/seotoaster-ui.css')
                ->prependStylesheet($this->websiteUrl . 'system/css/reset.css');
            echo $this->headLink();
	        echo $this->headStyle();
	        $this->jQuery()->enable();
            $this->jQuery()->uiEnable();
			$this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/external/smoke/smoke.min.js')
	            ->addJavascriptFile($this->websiteUrl . 'system/js/external/jquery/plugins/cookie/jquery.cookie.js')
			    ->addJavascriptFile($this->websiteUrl . 'system/js/internal/system.min.js');
	        echo $this->jQuery();
            $this->headScript()->setAllowArbitraryAttributes(true);
	        echo $this->headScript();
        ?>
    </head>
    <body>
        <noscript style="width: 100%; height: 100%; position: fixed; display: block; background: white; font-size: 150%; text-align: center; padding-top: 30%;">
	        JavaScript must be enabled at this point.<br/>
	        <a href="http://www.seotoaster.com/">seotoaster.com</a>
        </noscript>
        <?php echo $this->formHidden('website_url', $this->websiteUrl);?>
        <div class="seotoaster container <?php echo $this->placeholder('extraClasses'); ?>" id="<?php echo $this->placeholder('containerId'); ?>">
            <div class="header">
                <div class="closebutton">
                    <a class="close ticon-close" href="javascript:;" title="<?php echo $this->translate('Close'); ?>"></a>
                </div>
                <div class="grid_5">
                    <label class="grid_2 alpha omega" for="product-list-search"><?php echo $this->translate('Search');?>:</label>
                    <input class="grid_10 mt5px" type="text" name="search" id="search" placeholder="<?php echo $this->translate('search products');?>"/>
                </div>
                <?php echo $this->placeholder('headerContent'); ?>
            </div>
            <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>