<?php $this->headTitle($this->translate('Manage quotes')) ?>

<style type="text/css">
	table#quotes {
	    background-color: #efefef;
	}
	table#quotes thead tr {
	    border-bottom: 1px dashed #ccc;
	}
	table#quotes thead tr th {
	    white-space: nowrap;
	    color: #3C78A7;
	    text-align: left;
		padding: 5px;
	}
	table#quotes th.sortable {
		cursor: pointer;
	}
	table#quotes th.sortable::after{
	    color: #5f9ea0;
	    content: " \21D5";
	    display: inline;
    }
    table#quotes th.sortUp::after{
	    content: " \21E7";
    }
    table#quotes th.sortDown::after{
        content: " \21E9";
    }
	table#quotes tbody tr:hover td {
	    background-color:  #d3d3d3;
	    color: #3C78A7;
    }
	table#people-table tbody tr:hover td {
	    background-color:  #d3d3d3;
	    color: #3C78A7;
    }
    table#quotes td {
	    padding: 6px 2px;
    }
    table#quotes td.text-center{
	    text-align: center;
    }
    table#quotes tbody tr {
	    background-color: white;
	    border-bottom: 1px dashed #cccccc;
    }
	table#quotes a.table-nav {
	    margin: 10px 2px;
    }
    table#quotes a.table-nav:hover {
	    text-decoration: underline;
    }
</style>

<!-- quote template -->
<script id="quoteTemplate" type="text/x-jquery-tmpl">
	<td class="text-center">
		<input type="checkbox" name="selectedQuotes[]" value="${id}" title="Click to mark/unmark ${title}" {{if checked}}checked="checked"{{/if}} />
	</td>
	<td><a title="<?php echo $this->translate('Edit'); ?> ${title}" target="_blank" href="<?php echo $this->websiteUrl; ?>${id}.html">${title}</a></td>
	<td class="text-center">
		${$.datepicker.formatDate('dd M, yy', new Date(createdAt))}
	</td>
	<td class="text-center nopad">
		<select name="quoteStatus" class="quote-status" id="${id}">
			<option value="new" {{if status == 'new'}} selected="selected" {{/if}}>New</option>
			<option value="sent" {{if status == 'sent'}} selected="selected" {{/if}}>Sent</option>
			<option value="sold" {{if status == 'sold'}} selected="selected" {{/if}}>Sold</option>
			<option value="lost" {{if status == 'lost'}} selected="selected" {{/if}}>Lost</option>
		</select>
	</td>
	<td class="preview text-center">
		<a title="<?php echo $this->translate('Preview'); ?> ${title}" target="_blank" href="<?php echo $this->websiteUrl; ?>${id}.html?mode=preview"><img src="<?php echo $this->websiteUrl; ?>plugins/quote/web/images/preview.png" alt="<?php echo $this->translate('Preview'); ?> ${title}" /></a>
	</td>
	<td class="remove text-center">
		<a title="<?php echo $this->translate('Remove'); ?> ${title}" href="javascript:;" data-sid="${id}"><img src="<?php echo $this->websiteUrl; ?>system/images/delete.png" alt="delete"/></a>
	</td>
</script>

<?php
    $this->headScript()->setAllowArbitraryAttributes(true)
		    ->appendFile($this->websiteUrl . 'system/js/external/jquery/plugins/tmpl/jquery.tmpl.min.js')
            ->appendFile($this->websiteUrl . 'plugins/quote/web/js/libs/require/require.js', null, array('data-main' => $this->websiteUrl . 'plugins/quote/web/js/quote.js'));

	echo $this->noLayout ? $this->headScript() : '';
?>

<div class="ui-helper-clearfix" id="manage-quotes">
	<div><?php echo $this->translate('Search');?>&nbsp;<input type="text" id="quotes-search" name="quotesSearch" placeholder="<?php echo $this->translate('by title');?>" style="width: 200px"/></div>
	<table id="quotes" style="width: 100%">
		<thead>
			<tr class="mb10px">
				<th><?php echo $this->formCheckbox('quotes-check-all', null, array('title' => 'Check/Uncheck All'));?></th>
				<th data-sortkey="title" class="sortable"><?php echo $this->translate('Title'); ?></th>
				<th data-sortkey="created_at" class="sortable"><?php echo $this->translate('Date'); ?></th>
				<th data-sortkey="status" class="sortable"><?php echo $this->translate('Status'); ?></th>
				<th><?php echo $this->translate('Preview'); ?></th>
				<th><?php echo $this->translate('Remove'); ?></th>
			</tr>
		</thead>
		<tfoot>
			<tr>
	            <th colspan="4">
		            <?php echo $this->translate('with selected do');?>
		            <select id="mass-action" style="width: 250px">
			            <option value="0"><?php echo $this->translate('nothing');?></option>
			            <option value="deleteSelected"><?php echo $this->translate('delete');?></option>
			            <option value="markNew"><?php echo $this->translate('mark as new');?></option>
			            <option value="markSent"><?php echo $this->translate('mark as sent');?></option>
			            <option value="markSold"><?php echo $this->translate('mark as sold');?></option>
			            <option value="markLost"><?php echo $this->translate('mark as lost');?></option>
		            </select>
	            </th>
	            <th colspan="2">
		            <a href="#" id="quotes-previous" class="table-nav">&#8656;&nbsp;<?php echo $this->translate('previous');?></a>
		            <a href="#" id="quotes-next" class="table-nav"><?php echo $this->translate('next');?>&nbsp;&#8658;</a>
	            </th>
            </tr>
		</tfoot>
		<tbody>
			<tr>
		        <td colspan="5" class="text-center"><img src="<?php echo $this->websiteUrl;?>/system/images/loading.gif"/></td>
			</tr>
		</tbody>
	</table>
</div>