<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><?php echo $this->translate('View product and manage options'); ?></title>
		<meta name="description" content="<?php echo $this->translate('Manage product options'); ?>">
		<meta name="author" content="SEOTOASER 2">
		<meta name="viewport" content="width=device-width">

		<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/reset.css')
                ->appendStylesheet($this->websiteUrl . 'system/css/grid.css')
                ->appendStylesheet($this->websiteUrl . 'system/uithemes/seotoasterui/seotoasterui.css')
                ->appendStylesheet($this->websiteUrl . 'system/css/seotoaster.css')
                ->appendStylesheet($this->websiteUrl . 'system/js/external/smoke/smoke.css')
                ->appendStylesheet($this->websiteUrl . 'system/js/external/smoke/themes/toaster.css')
				->appendStylesheet($this->websiteUrl . 'plugins/quote/web/css/manage.options.css'); ?>
        <?php echo $this->headLink(); ?>

		<!-- quote template -->
		<script id="singleProductTemplate" type="text/x-jquery-tmpl">
			<div class="product-data grid_4 h300">
				<p id="product-name">${name}</p>
				<img src="{{if photo}}${'/media/'+photo.replace('/', '/small/')}{{else}}/system/images/noimage.png{{/if}}" width="150" alt="${name}" />
				<p><span><?php echo $this->translate('sku');?>: </span><span>${sku}</span></p>
				<p><span><?php echo $this->translate('brand');?>: </span><span>${brand}</span></p>
			</div>
			<div data-productid="${id}" class="product-options-listing h300 grid_8">
				{{each(index, val) defaultOptions}}
					{{if val.type == 'dropdown'}}
						<div class="product-option option-dropdown">
							<label for="product-${id}-option-${val.id}">${val.title}</label>
							<select name="selection" id="option-${val.id}">
								{{each(key, value) val.selection}}
									<option value="${value.id}" {{if value.isDefault == '1'}} selected="selected" {{/if}}>${value.title} (${value.priceSign}${value.priceValue} {{if value.priceType == 'percent'}}%{{/if}})</option>
								{{/each}}
							</select>
							<input type="hidden" name="option" value="${val.id}">
						</div>
					{{/if}}
				{{/each}}
			</div>
		</script>

	</head>
	<body>
		<input type="hidden" id="pluginUrl" name="pluginUrl" value="<?php echo trim($this->websiteUrl, ' /').$this->url(array('run'=>''));?>" />
	    <input type="hidden" id="websiteUrl" name="websiteUrl" value="<?php echo $this->websiteUrl;?>" />
		<input type="hidden" id="website_url" name="websiteUrl" value="<?php echo $this->websiteUrl;?>" />
		<input type="hidden" id="product-id" value="<?php echo $this->productId; ?>" />
		<div class="seotoaster container_12 h400" id="manage-product-options">
			<div class="header" style="overflow:hidden;">
				<div class="closebutton">
				    <span class="close"><?php echo $this->translate('Close'); ?></span>
				</div>
				<?php echo $this->translate('Manage product options'); ?></a>
			</div>
			<div id="manage-product-options-main" class="grid_12 h310">

			</div>
			<div class="grid_12 mt10px" style="text-align: right;">
				<a data-pid="<?php echo $this->productId; ?>" href="javascript:;" id="save-options"><?php echo $this->translate('Save options'); ?></a>
			</div>
   	    </div>
	</body>
	<?php
        $this->headScript()->setAllowArbitraryAttributes(true)
                ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js')
                ->appendFile('https://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js')
                ->appendFile($this->websiteUrl.'system/js/external/jquery/plugins/tmpl/jquery.tmpl.min.js')
                ->appendFile($this->websiteUrl . 'system/js/external/smoke/smoke.min.js')
                ->appendFile($this->websiteUrl . 'plugins/quote/web/js/libs/require/require.js', null, array('data-main' => $this->websiteUrl . 'plugins/quote/web/js/options.js'))
                ->appendFile($this->websiteUrl . 'system/js/internal/system.js');
        echo $this->headScript();
    ?>
</html>
