<?php
    $this->placeholder('headerContent')->set('Manage options');
    $this->placeholder('extraClasses')->set('refreshOnClose');
    $this->placeholder('containerId')->set('manage-product-options');
?>


<div id="manage-product-options-main" class="grid_12 h310"></div>
<div class="grid_12" style="text-align: right;padding: 5px 0;">
    <a data-qid="<?php echo $this->quoteId; ?>" href="javascript:;" id="save-options"><?php echo $this->translate('Save options'); ?></a>
</div>
<style type="text/css">
    .product-item {overflow: hidden;position: relative;}
    .product-data img {
        max-height: 231px;
    }
    #product-name {
        position: absolute;
        background: rgba(0, 0, 0, 0.7);
        padding: 7px;
        color: white;
        width: 218px;
        text-align: center;
    }
    .product-details {
        position: absolute;
        background: rgba(0, 0, 0, 0.7);
        color: white;
        padding: 7px;
        width: 218px;
    }
</style>

<?php
    $this->headScript()->setAllowArbitraryAttributes(true)
        ->appendFile($this->websiteUrl . 'plugins/shopping/web/js/libs/require.min.js', null, array('data-main' => $this->websiteUrl . 'plugins/quote/web/js/options.js'));
    echo $this->headScript();
?>
