<?php
    $this->placeholder('headerContent')->set('Manage options');
    $this->placeholder('extraClasses')->set('refreshOnClose');
    $this->placeholder('containerId')->set('manage-product-options');
?>


<div id="manage-product-options-main" class="grid_12 h310"></div>
<div class="grid_12 mt10px" style="text-align: right;">
    <a data-qid="<?php echo $this->quoteId; ?>" href="javascript:;" id="save-options"><?php echo $this->translate('Save options'); ?></a>
</div>

<?php
    $this->headScript()->setAllowArbitraryAttributes(true)
        ->appendFile($this->websiteUrl . 'plugins/shopping/web/js/libs/require.min.js', null, array('data-main' => $this->websiteUrl . 'plugins/quote/web/js/options.js'));
    echo $this->headScript();
?>
