<div id="products-container" class="seotoaster f-container refreshOnClose">
    <?php
    $quoteSearch = '<div class="grid_5"><input type="text" name="search" id="search" placeholder="'.$this->translate('Search by name, sku, mpn or tags').'"/></div>';

    echo $this->partial(
        'admin' . DIRECTORY_SEPARATOR . '_header.phtml',
        array(
            'innerHeaderHtml' => $quoteSearch
        )
    ); ?>
    <div id="products" class="f-content column_8" data-emptymsg="<?php echo $this->translate('Nothing Found'); ?>"></div>
    <div class="f-footer">
        <div class="products-paginator grid_9 mt10px"></div>
        <button id="save-btn" class="btn add-products ticon-save grid_3"><?php echo $this->translate('Add products and close'); ?></button>
        <!--p class="message info grid_3 pt0px pb0px omega mt15px"><i class="ticon-info-sign"></i> <?php //echo $this->translate('Select 1 or more products&nbsp'); ?></p-->
    </div>
    <input type="hidden" id="checkedProducts" value=""/>
</div>
<?php
        $this->headScript()->setAllowArbitraryAttributes(true)
            ->appendFile($this->websiteUrl . 'plugins/shopping/web/js/libs/require.min.js', null, array(
                    'data-main' => $this->websiteUrl . 'plugins/quote/web/js/product.js'
                ));
        echo $this->headScript();
?>


