<div class="mt10px">
    <p>
        <label><?php echo $this->translate('Additional emails');?> <a href="javascript:;" class="ticon-info tooltip icon18" title="<?php echo $this->translate('You can enter emails separated by comma. ex')?>: John@mail.com,Doe@mail.com"></a> : </label>
        <input type="text" name="additional-emails" id="additional-emails" value="" />
    </p>
    <?php if (!empty($this->opportunityStages)):?>
        <div class="flex-row f-middle">
            <div class="flex_8 flex-row f-middle f-omega opportunity-processing-block">
                <select name="stageId" id="email-opportunity-stage-id" class="flex_6 f-omega hidden">
                    <option value="0"><?php echo $this->translate('Select opportunity stage');?></option>
                    <?php foreach ($this->opportunityStages as $opportunityId => $opportunityStage) :?>
                        <?php if (!in_array($opportunityId, array(1, 100))):?>
                            <option value="<?php echo $opportunityId;?>" <?php echo ($opportunityId == '60')?'selected':'';?>><?php echo $opportunityStage;?> <?php echo $opportunityId;?> %</option>
                        <?php endif;?>
                    <?php endforeach;?>
                </select>
            </div>
        </div>
    <?php endif;?>
</div>