<?php if(!empty($this->options)): ?>

	<?php foreach($this->options as $title => $optData): ?>
	    <p>
            <span class="option-title"><?php echo $title; ?>: </span>
		    <?php echo $optData['title']; ?>
            <?php if(isset($optData['selection'])): ?>
                <span><?php echo $optData['selection']; ?></span>
            <?php else: ?>
                <?php echo '(', $optData['priceSign'], $this->currency($optData['priceValue']), ')'; ?>
                <?php echo '(', $optData['weightSign'], $optData['weightValue'], ' ', $this->weightSign, ')'; ?>
            <?php endif; ?>
	    </p>
	<?php endforeach; ?>

<?php endif; ?>
<?php if(Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_ADMINPANEL)): ?>
	<a href="javascript:;" data-pwidth="600" data-pheight="404" class="tpopup" data-url="<?php echo $this->websiteUrl; ?>plugin/quote/run/options/co/<?php echo $this->options[0]['id'];?>/qid/<?php echo $this->quoteId; ?>/pid/<?php echo $this->productId;?>">
		<strong><?php echo $this->translate('Manage options'); ?></strong>
	</a>
<?php endif; ?>
