<?php if($this->editAllowed && $this->unitPrice == 'unit'): ?>
    <input data-pid="<?php echo $this->productId; ?>" data-scope="quote-item" data-type="price" class="quote-recalculate price-unit" type="text" value="<?php echo Zend_Locale_Format::toFloat($this->price, array('precision' => 2, 'locale' => new Zend_Locale($this->currency()->getCurrency()->getLocale()))); ?>" />
<?php else: ?>
    <span data-pid="<?php echo $this->productId; ?>" class="price-<?php echo (($this->unitPrice) ? 'unit' : 'total'); ?>"><?php echo $this->currency($this->price); ?></span>
<?php endif; ?>
